### ISSUE TITLE
Doesn`t load theme in vaadin 8 branch

### ISSUE THREAD

**Issue by zotona** [christoph-frick/vdecl#1]
styles not loaded, see [https://gyazo.com/823275d31f3834224fd7e57850f5dee8](https://gyazo.com/823275d31f3834224fd7e57850f5dee8)
in jar its present https://gyazo.com/110a4c7136229d57f93d5eb346db4d02
https://gyazo.com/d599b709c82a7ac39d08decd33723a6b

it seems vaadinCompile write emty scss files..
P.S. Very cool tool! Thanks!

**Comment by christoph-frick** [comment]
Thanks for the feedback.  I'll try to reproduce this. That branch *works for me*™

**Comment by christoph-frick** [comment]
@zotona when trying out, note the default artifact now is vdecl.war (just rename it or use it as before) and do a CTRL-F5 reload since at least my browser insisted on using the cached, empty css file.
