### ISSUE TITLE
IllegalStateException: Push is not available. See previous log messages for more information.

### ISSUE THREAD

**Issue by nandotorterolo** [christoph-frick/vdecl#2]
Did you find a workaround to avoid this issue.?

[issue.txt](https://github.com/christoph-frick/vdecl/files/998156/issue.txt)

Thanks

**Comment by christoph-frick** [comment]
I have made the vaadin-8 branch the new master now.  The problem there is fixed.  If you need vaadin7 it should be as easy as changing the version in the `build.gradle`.  Note, that the artifact now is `build/libs/vdecl.war` but runs the same as with the jar before.

**Comment by nandotorterolo** [comment]
Thanks for your help.
Compile problems with version , vaadinVersion = '7.6.5'
Cause ValueProvider used in HomeView.groovy is supported since 8.0
Since: https://vaadin.com/api/8.0.5/com/vaadin/data/ValueProvider.html

> :compileJava
:compileGroovy
startup failed:
/home/user/Ucu/vdecl/src/main/groovy/vdecl/ui/HomeView.groovy: 3: unable to resolve class com.vaadin.data.ValueProvider
 @ line 3, column 1.
   import com.vaadin.data.ValueProvider

**Comment by christoph-frick** [comment]
@nandotorterolo Yeah of course.  Sorry that was not correct (changing the version is not longer working as for the minor v7 releases).  I have put the changes to master over in the `vaadin-7` branch.
